name: romantic_analysis
description: Lint rules for Dart and Flutter used internally at RomanticEra
version: 0.0.1-dev.0
repository: https://github.com/RomanticEra/romantic_analysis

environment:
  sdk: ">=2.14.0 <3.0.0"
dependencies:
  all_lint_rules_community: ^0.0.5